### ISSUE TITLE
[CAD] - Consider reducing number of bolts

### ISSUE THREAD

**Issue by stuartpittaway** [index-machines/index#328]
Parts
FDM_0006_00_x_motor_mount
FDM_0013_00_x_idler_mount

Have a 4 bolt hole pattern, consider reducing to 2 bolt pattern as 4 bolts are not required given the stress loads these parts have.

This would reduce cost and weight on the gantry.

**Comment by sphawes** [comment]
That's a good point, two bolts on each side might be a bit overkill. I added that many originally because I wanted to have two mounting points for the Y gantry umbilical mount, but that's not super necessary. Let's default to keeping this many for now. If we find the extra weight is causing issues with how fast we can move, reducing the amount of hardware is a safe change to make for fastener kits, and could happen any time. I'll close for now, but this would be a good optimization to make later if we run into speed issues!
