### ISSUE TITLE
[CAD] - Suggestion - Mount X gantry rail from top

### ISSUE THREAD

**Issue by stuartpittaway** [index-machines/index#329]
Whilst building the index it occurred to me that the X rail 20x20 would be easier to assemble if it were installed from the top rather than from the bottom.

If top mounted, each site of the gantry (FDM0005 & FDM0008) could be attached to the rail first, then the 20x20 rail slotted into the top of these parts and screwed in.

If this were done, the X rail would likely increase in height giving more Z clearance (not sure if this is good or bad!)

This change would also facilitate removal of the X carriage without disassembly of the wheels etc.

**Comment by sphawes** [comment]
That certainly would make it easier to get the rail out! The thing I'm mainly concerned with about this is that adjusting the position of the Y gantries on the X rail gets very difficult. If we're dropping the rail in from the top, we lose the top surface that we might use to bolt it to the Y gantries. The sides of the x axis rail can't be mounted to because of the GT2 timing belt, so the bottom face is the only option. Being able to tighten and loosen that while adjusting the y gantries' position on the x rail will be quite tricky, and likely get in the way of the rollers quite a bit.
