### ISSUE TITLE
No z-gantry-right design in the 'freecad' branch

### ISSUE THREAD

**Issue by JudgeBeeb** [index-machines/index#80]
There is no z-gantry-right design in the 'freecad' branch. The component shown in the 'Switching the Index PnP to FreeCAD!' video is not a precise mirror image of the z-gantry-left part and is also different from the corresponding part in the 'master' branch.

**Comment by G-Pereira** [comment]
There are several commits since the day that video was published (12th December) probably it was improved already!
The parts on the freecad branch are the most up to date. Some days ago a script was added to generate STL automatically to avoid having out of date STL files in the repository, so you need to download them again.
Can this issue be closed?

**Comment by G-Pereira** [comment]
@JudgeBeeb Can this issue be closed?

**Comment by JudgeBeeb** [comment]
This is still a live issue. The part is missing from the 'freecad' branch.

**Comment by daveismith** [comment]
Is it not just a mirror of the left part? That's what I ended up printing and am planning to install. Agree it should be in the cad though so that the STLs are getting exported.

**Comment by JudgeBeeb** [comment]
I too have printed a mirror of the left part. But if you look closely in the video, the part Stephen printed is not a mirror of the left part. Not sure why though.

**Comment by G-Pereira** [comment]
Now I see what you mean! @sphawes has plans to revisit paste extrusion / second head later when everything else is rock solid. This is on his low priority list.
Let's keep this open to remind us to add that part!

**Comment by G-Pereira** [comment]
Fixed!
